name: build and push docker imagedss
on:
push:
 branche:
  - dev-branch 
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
  - name: checkout code 
    uses: actions/checkout@v2
  - name: action-login 
    uses: docker/login-action@v2  
    with:
      username: ${{secrets.DOCKER_USERNAME}}
      password: ${{secrets.DOCKER_PASSWORD}}   
  - name: build and push docker image 
    run: docker build -t betrand1999/myapp .
  - name: tag docker image 
    run: docker tage betrand1999/myapp:latest       
    
  - name: push docker image
    run: docker push betrand1999/myapp:latest  
